---
# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Allow long code blocks
  code_blocks: false
  # Allow long tables
  tables: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  # Allow different nesting levels to use same heading text
  allow_different_nesting: true

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML elements
  allowed_elements:
    - br
    - img

# MD041/first-line-heading - First line in a file should be a top-level heading
MD041:
  # Exclude files that are likely to be included in other files
  exclude:
    - _*.md

# Made with Bob
