{{- /*
Copyright IBM, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and (not (empty .Values.agent.cloudability.secret.existingSecret)) .Values.agent.cloudability.secret.create }}
{{- fail "Cannot set both agent.cloudability.secret.existingSecret and agent.cloudability.secret.create" }}
{{- end }}

{{- if .Values.agent.cloudability.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudability.secret.name" . | trim }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: finops-agent
    app.kubernetes.io/component: config
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" .) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  CLOUDABILITY_KEY_ACCESS: {{ .Values.agent.cloudability.secret.cloudabilityAccessKey | b64enc | quote }}
  CLOUDABILITY_KEY_SECRET: {{ .Values.agent.cloudability.secret.cloudabilitySecretKey | b64enc | quote }}
  CLOUDABILITY_ENV_ID: {{ .Values.agent.cloudability.secret.cloudabilityEnvId | b64enc | quote }}
{{- end }}
