{{- /*
Copyright IBM, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and (not (empty .Values.global.cspPricingApiKey.existingSecret)) .Values.global.cspPricingApiKey.apiKey }}
{{- fail "Cannot set both cspPricingApiKey.existingSecret and cspPricingApiKey.apiKey" }}
{{- end }}

{{- if and (not (empty .Values.global.cspPricingApiKey.existingSecret)) .Values.global.cspPricingApiKey.useDefaultApiKey }}
{{- fail "Cannot set both cspPricingApiKey.existingSecret and cspPricingApiKey.useDefaultApiKey" }}
{{- end }}

{{- define "finops-agent.cspPricingApiKeyWarning" }}
{{- if and .Values.global.cspPricingApiKey.apiKey .Values.global.cspPricingApiKey.useDefaultApiKey }}
Both cspPricingApiKey.apiKey and cspPricingApiKey.useDefaultApiKey are set. apiKey will be used and useDefaultApiKey will be ignored.
{{- end }}
{{- end }}

{{- if or .Values.global.cspPricingApiKey.apiKey .Values.global.cspPricingApiKey.useDefaultApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finops-agent.cspPricingApiKeySecretName" . | trim }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: finops-agent
    app.kubernetes.io/component: config
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" .) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  CSP_PRICING_API_KEY: {{ .Values.global.cspPricingApiKey.apiKey | default "AIzaSyDXQPG_MHUEy9neR7stolq6l0ujXmjJlvk" | b64enc | quote }}
{{- end }}
