# Copyright IBM, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: FinOps
  licenses: Apache-2.0
apiVersion: v2
appVersion: v0.0.15
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: The IBM FinOps Agent collects usage and cost data from items running in the kubernetes cluster. These can then be consumed by Cloudability(TM) and Kubecost(TM).
home: https://github.com/kubecost/finops-agent-chart
#icon: TODO - which icon to use?
keywords:
- finops
- ibm
- agent
- cloudability
- kubecost
maintainers:
- name: IBM, Inc. All Rights Reserved.
  url: https://ibm.com
name: finops-agent
sources:
- https://github.com/kubecost/finops-agent-chart
version: 0.1.1
