# Copyright IBM, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: FinOps
  licenses: Apache-2.0
  kubecost.com/version: 3.0.0-test.0
apiVersion: v2
appVersion: v1.0.0-rc.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: The IBM FinOps Agent collects usage and cost data from items running in the kubernetes cluster. These can then be consumed by Cloudability(TM) and Kubecost(TM).
home: https://github.com/kubecost/finops-agent-chart
icon: https://raw.githubusercontent.com/kubecost/finops-agent-chart/767dfe7d3c4c261b754c14be5d14a131ac575acd/resources/ibm_logo_blue.png
keywords:
- finops
- ibm
- agent
- cloudability
- kubecost
maintainers:
- name: IBM, Inc. All Rights Reserved.
  url: https://ibm.com
name: finops-agent
sources:
- https://github.com/kubecost/finops-agent-chart
version: 1.0.0-rc.0
