global:
  ## clusterId is used to identify the cluster in the FinOps Agent
  ## when using the same cluster names in different regions, we suggest appending the region to the clusterId
  clusterId: globally-unique-cluster-id
agent:
  cloudability:
    enabled: true
    secret:
      cloudabilityAccessKey: ""
      cloudabilityEnvId: ""
      cloudabilitySecretKey: ""
      create: true
    uploadRegion: us-west-2
