name: Publish Helm Chart

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: Kubecost-Linux-Small-x86
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
           git config --local user.email "github-actions[bot]@noreply.example.com"
           git config --local user.name "github-actions[bot]"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0


      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts/finops-agent
          config: .github/workflows/cr.yaml
          skip_packaging: false
          skip_upload: false
          packages_with_index: true
          gh_pages_branch: gh-pages
      